export { default as Home } from './Home'
export { default as Settings } from './Settings'
export { default as User } from './User'
export { default as Products } from './Products'
export { default as Shop } from './Shop'
